export const NEW_HOTEL_REQUEST = 'NEW_HOTEL_REQUEST';
export const NEW_HOTEL_SUCCESS = 'NEW_HOTEL_SUCCESS';
export const NEW_HOTEL_FAILURE = 'NEW_HOTEL_FAILURE';
export const SET_USER_DATA = 'SET_USER_DATA';