export const NEW_HOTEL_REQUEST = 'NEW_HOTEL_REQUEST';
export const NEW_HOTEL_SUCCESS = 'NEW_HOTEL_SUCCESS';
export const NEW_HOTEL_FAILURE = 'NEW_HOTEL_FAILURE';
export const SET_USER_DATA = 'SET_USER_DATA';
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAILURE = "GET_ALL_PRODUCTS_FAILURE";